### ISSUE TITLE
Add HealthcareServices resources - generate from existing Organization/PractitionerRole resources

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#12]
Add HealthcareService sample data.

1. Assess and select the personas from Services Australia to be HealthcareServices using Organization & PractitionerRole
2. Assess initial gaps, add any additional HealthcareServices for 'minimum' set
3. Design and develop those HealthcareServices instances (assume csv file)

**Comment by heathfrankel** [comment]
HealthcareService instances have been generated from AU Core Sample Data HealthcareService.csv derived from Services Australia data. 
See commit [8a473a0](https://github.com/hl7au/au-fhir-test-data/commit/8a473a068d333225817d726f3fd1bad7786fbe43).
There are references to providedBy Organization and location.
There are is no references to PractitionerRoles in this resource type.
