### ISSUE TITLE
PractitionerRole: Add Services Australia provided Medicare Provider Numbers

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#15]
Permission has been granted from Services Australia to publish the Medicare Provider Numbers. Please add and update the README.

**Comment by heathfrankel** [comment]
I have used the DHCA_TestProviders_Presciber numbers_20240219.xlsx file located in https://csiroau.sharepoint.com/sites/DoHACCSIROdigitalhealthcollaborationspace/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=rdB17q&cid=830dd053%2D34dc%2D4b97%2D8d2c%2D4a536bcb5eb3&FolderCTID=0x0120000F26A9422A29BF469B9EF2D4E54FC284&id=%2Fsites%2FDoHACCSIROdigitalhealthcollaborationspace%2FShared%20Documents%2FAU%20Core%20TDG%2FTest%20Data%2FDHCA%5FTestData%20with%20identifiers%20%2D%20approved%2020240405&viewid=48e2dbcd%2D6a9a%2D4167%2D9e0d%2Df7e88d3f2489 and copied over the top of the DHCA_TestProviders_Presciber numbers_20240224.xlsx file located in the parent folder.
The latter is referenced by the AU Core Test Data.xlsx file, and I didn't want to have to update all the formulas to use a different file name.
The Medicare Provider Numbers now appear in the PractitionerRole generated test data.

**Comment by heathfrankel** [comment]
Done
