### ISSUE TITLE
PractitionerRole: Correct ANZSCO codesystem url

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#18]
There is an issue in the mapping for PractitionerRole.code.system

These are all ANZSCO codes but the system url varies across the set and is incorrect.

Correct url is: http://www.abs.gov.au/ausstats/abs@.nsf/mf/1220.0

But for example in:
* https://github.com/hl7au/au-fhir-test-data/blob/master/generated/Organization-annie-river-practice.json the url is http://www.abs.gov.au/ausstats/abs@.nsf/mf/1292.13
* https://github.com/hl7au/au-fhir-test-data/blob/master/generated/Organization-appin-pharmacy.json the url is http://www.abs.gov.au/ausstats/abs@.nsf/mf/1292.24

**Comment by StephThaoOng** [comment]
Fixed.
