### ISSUE TITLE
Patient: add gender identity, individual pronous, and sex assigned at birth

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#19]
Enhance the set of Patient sample data to:
1. add individual pronouns to 20% of the set
2. add gender identity to 20% of the set
3. add sex assigned at birth to 20% of the set

Ensure:
1. avoid biased data and provide variation e.g. gender, pronoun, sex should not consistently be always male, him/his, male
2. have some resources with just one of the above, some with two, some with all
3. the patient resources that have clinical resources associated end up with some patients that have one, two, or three of the inclusions

**Comment by michael-wilson-au** [comment]
Patient.csv contains patients with pronouns and recorded sex or gender however they are not mapped to the generated json.  Patient test data with pronouns and recorded sex or gender is required for AU Core test events.

**Comment by StephThaoOng** [comment]
23/9 Sparked Infra&Tooling meeting: Suggested @JayMurdoch could support with resolving this ticket and use as a test run for [Test Data - Creating and Generating using Spreadsheet](https://confluence.hl7.org/display/HA/Test+Data+-+Creating+and+Generating+using+Spreadsheet) instructions. 
@Heath is happy to support with any queries about the test data spreadsheet.

**Comment by StephThaoOng** [comment]
24/9: De-assigned pending project planning

**Comment by StephThaoOng** [comment]
@heathfrankel I've added gender identity, individual pronouns, and sex assigned at birth to the Patient sheet of [AU Core Test Data.xlsx](https://csiroau.sharepoint.com/:x:/r/sites/DoHACCSIROdigitalhealthcollaborationspace/Shared%20Documents/AU%20Core%20TDG/Test%20Data/AU%20Core%20Test%20Data.xlsx?d=we05aefbb8e83461ba4c55b91733700a3&csf=1&web=1&e=DoWgzY) that meet the reqs originally noted by dt-r.

I've added to new columns (see CE and CH) to this sheet. 
Can I please hand over to update the Csv2FhirMapping?
