### ISSUE TITLE
Add Procedure resources

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#20]
Add initial set of Procedure sample data.

1. Assess and select the Patients to add procedure data to (want to build out patients that already have data)
2. Assess early requirements and what the set of Procedure resources for 'minimum' set would be that addresses AU Core implementation guidance and Must Support
3. Design and develop those Procedure instances (assume csv file)
4. Expectation is this is at lest 5 Procedure resources

**Comment by StephThaoOng** [comment]
Current status: **Three** resources added with coverage of Must Support elements shown in table below. **Two** more resources to add, then ticket can be closed. 



<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ONG019/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ONG019/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">


</head>

<body link="#467886" vlink="#96607D">


Must   Support element | Reference Type | Current AU FHIR   Test Data Coverage
-- | -- | --
Procedure.status |   | yes
Procedure.code |   | yes
Procedure.subject |   | yes
Procedure.encounter |   | yes
Procedure.performedDateTime |   | yes
Procedure.performedPeriod |   |  
Procedure.performedString |   |  
Procedure.performedAge |   |  
Procedure.performedRange |   |  
Procedure.reasonCode |   | yes
Procedure.reasonReference | Reference(AU Core   Condition) | yes
Procedure.reasonReference | Reference(Observation) |  
Procedure.reasonReference | Reference(AU Core   Procedure) |  
Procedure.reasonReference | Reference(DocumentReference) |  



</body>

</html>
