### ISSUE TITLE
PractitionerRole: Add PractitionerRole.specialty

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#23]
PractitioneRole.specialty is not present in the PractitioneRole instances that correspond to Services Australia provided data. This should be added, it is must support in AU Core.

**Comment by StephThaoOng** [comment]
@dt-r 
cc: @heathfrankel 

Can I please get some guidance on mapping SA data to FHIR? 

Proposed SA attribute --> AU Core PractitionerRole element in [AU Core Test Data](https://csiroau.sharepoint.com/:x:/r/sites/DoHACCSIROdigitalhealthcollaborationspace/Shared%20Documents/AU%20Core%20TDG/Test%20Data/AU%20Core%20Test%20Data.xlsx?d=we05aefbb8e83461ba4c55b91733700a3&csf=1&web=1&e=q3Ibov)
`PROVIDER SPECIALTY CODE -->  specialty1_coding1_code` 
`SPECIALTY TYPE --> specialty1_coding1_display`
`SPECIALISATION CODE --> specialty1_coding2_code`
`SPECIALISATION DESCRIPTION --> specialty1_coding2_display`

Also need to check if new columns should be added for specialty1_coding3 to be populated with the closest match from Clinical Specialty value set: https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/clinical-specialty-1

**Comment by dt-r** [comment]
@StephThaoOng, please advise which terminology i.e. ANZSCO, LOINC, SNOMED, etc. is proposed here.

I want at least one if not more SNOMED CT specialities where we can consider a practitioner to have a corresponding speciality from the preferred valueset for PractitionerRole.specialty. If that is not suitable then from wider SNOMED CT. Michael Osborne can perform that for you. This is the implementation advice in HL7 AU implementation guides.

There may additionally be proposed that some of the Services Australia provided ANZSCO values for a provider populate one or more codings in PractitionerRole.specialty. If that is so, please confirm in the comments in that those values are not already used in PractitionerRole.code.

**Comment by StephThaoOng** [comment]
@Michael O (invite impending)
In the FHIR Test Data csv: 
https://csiroau.sharepoint.com/sites/DoHACCSIROdigitalhealthcollaborationspace/Shared%20Documents/AU%20Core%20TDG/Test%20Data/AU%20Core%20Test%20Data.xlsx?web=1  
Can you please map sheet "DHAC_TestProviders_combined" column F "SPECIALTY TYPE" (11 entries) to PractitionerRole.specialty preferred terminology binding. 
This coding is to populate Sheet "PractitionerRole" column AF-AH "specialty1_coding1".

Can you please action this favour today?  

@dt-r Thanks for the clarification. Please note that until the Smile CDR fix for multiple codings is released, loading the Sparked dev FHIR server with test data enriched with multiple codings is blocked.

**Comment by StephThaoOng** [comment]
> @MichaeOsbourne In the FHIR Test Data csv: https://csiroau.sharepoint.com/sites/DoHACCSIROdigitalhealthcollaborationspace/Shared%20Documents/AU%20Core%20TDG/Test%20Data/AU%20Core%20Test%20Data.xlsx?web=1 Can you please map sheet "DHAC_TestProviders_combined" column F "SPECIALTY TYPE" (11 entries) to PractitionerRole.specialty preferred terminology binding. This coding is to populate Sheet "PractitionerRole" column AF-AH "specialty1_coding1".
> 
> Can you please action this favour today?
> 
> @dt-r Thanks for the clarification. Please note that until the Smile CDR fix for multiple codings is released, loading the Sparked dev FHIR server with test data enriched with multiple codings is blocked.

@MichaelOsbourne Additional request as discussed - can you please derive the PractitionerRole.specialty from the Service Australia (SA) provide data for the following PractitionerRoles:

- generalpractitioner-guthridge-jarred
- cardiologist-felmingham-emma
- cardiologist-sutherland-sallie
- generalpractitioner-harding-diana
- renalmedicine-mackay-darleen
- nephrologist-darleen-mackay
- nursepractitioner-osmond-deadra
- pharmacist-ford-dean
- registerednurses-sinclair-forrest
- cardiothoracicsurgeon-manning-meg
- surgeongeneral-fryer-chau
- midwife-kendall-dallas

The SA provided SPECIALTY/SPECIALISATION data will map to PractitionerRole.code.
For the FHIR test data set, PractitionerRole.**specialty** coding will be added by us, selected from its [preferred SNOMED CT value set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/clinical-specialty-1). 
In future, once the multiple codings fix is applied, we can enrich PractitionerRole.**code** with codes from its [preferred SNOMED CT value set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/practitioner-role-1).

**Comment by heathfrankel** [comment]
@dt-r The PractitionerRole.specialty codes from clinical-speciality-1 valueset are not really aligned with the ANZSCO codes provided in the SA data. 
For example, we get 253512 Cardiothoracic Surgeon as the ANZSCO code, which we map to PractitionerRole.code.
This could be mapped to SNOMED 309369000 Cardiothoracic surgeon as a second code.coding, but currently we won't be able to upload this to the reference server.
However for speciality, the clinical-specialty-1 value set has a concept of 394603008 Cardiothoracic surgery, but these are really not associated concepts. They are in completely different hierarchies.

So although they have a similar, but different description, the latter should not be derived explicitly from the ANZSCO code. 
Having said that, we have asked Michael to give us some clinical speciality codes that we can use in our test data as augmented data.

**Comment by mjosborne1** [comment]
I have added specialties from the clinical specialty ValueSet to the examples indicated in @StephThaoOng 's comment.

**Comment by mjosborne1** [comment]
Added ANZCO mapping to SNOMED CT clinical specialties - noting that 12 codes had no mapping.

**Comment by dt-r** [comment]
> correspond to Services Australia provided data

Yes, I understand. I am looking for specialty codes that would apply to the Pracitioners we've created. In terms of clarifying the request for 'correspond to Services Australia provided data' is about the persona as a whole and shouldn't conflict. It should be the kind of specialty you would expect for that persona. I do not expect that those codes are equivalent, I agree that these are not the same concept.

**Comment by heathfrankel** [comment]
I have added Specialty to majority of PractitionerRole resources derived from Services Australia Provider Specialty that Michael mapped to clinical-specility-1 ValueSet.

**Comment by heathfrankel** [comment]
See Commit [a28fcba](https://github.com/hl7au/au-fhir-test-data/commit/a28fcbadd255fac0d690701ff1702de6d6063006)
