### ISSUE TITLE
Enrich Observation Diagnostic Result resources with 'Must Support' data

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-test-data#35]
Enrich Observation Diagnostic Result resources with 'Must Support' data so the below test is not skipped.

> Test 1.11.20 All must support elements are provided in the Observation resources returned.
> 
> Could not find 'identifier', 'performer', 'interpretation', 'note', 'referenceRange', 'referenceRange.low', 'referenceRange.high', 'referenceRange.type', 'referenceRange.text', 'hasMember', 'component', 'component.code', 'component.value[x]' element(s) in the 1 provided Observation resource(s). To prevent this issue, please add the missing must support elements to at least one Observation resource on the server.

**Comment by heathfrankel** [comment]
[FHIR-46737](https://jira.hl7.org/browse/FHIR-46737) has removed the following elements as Must Support for R1:
- identifier
- note
- method
- reference range
- interpretation

Therefore this issue now only applies to:
- performer
- hasMember
- component
- component.code
- component.value[x]

The new Observation/hearing-threshold-1 added in [#25](https://github.com/hl7au/au-fhir-test-data/issues/25) includes performer.
The Observation/bonedensity includes hasMember.

A new diagnosticresult example with component elements is the only scenario remaining.

**Comment by heathfrankel** [comment]
A new Observation-glasgow-coma-scale example has been added to provide an example au-core-diagnosticresult with components.

Currently this example is failing upload due to missing '{scale}' in UCUM fragment, otherwise, the example appears valid.
