### ISSUE TITLE
Remove IHIs, HPI-Is, HPI-Os from non-Services Australia provided examples

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#4]
remove from:
- Organization-bobrester-medical-center
- Organization-adv-hearing-care
- Organization-hospital-au
- Organization-pharmacy
- Patient-wang-li
- Practitioner-pharmacist
- Practitioner-cardy-igist
- Practitioner-surgeon-david
- Practitioner-sandyson-sandy

**Comment by heathfrankel** [comment]
ABove resources updated.
Also removed HI identifiers located in references and identifiers with hpio scoped system
