### ISSUE TITLE
Remove non Services Australia provided HPI-Is and HPI-Os from postman data

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#5]
[Sparked eRequesting Test Data.postman_collection.json](https://github.com/hl7au/au-fhir-test-data/blob/master/Postman/Sparked%20eRequesting%20Test%20Data.postman_collection.json) contains non Services Australia provided data. It uses Patients, Practitioners, Organizations that are not in HL7 AU Test Data.

This postman collection needs to be refactored to use HL7 AU Test Data.

**Comment by heathfrankel** [comment]
I believe the non SA assigned HPIs have been removed.
However, as we remove the non SA entities from the test data, these will need to be removed from the POSTman data
