### ISSUE TITLE
Add additional AllergyIntolerance resources for the patients for the patients of interest

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#55]
Patients of interest are those in inferno tests: baratz-toni, irvine-ronny-lawrence, italia-sofia, howe-deangelo, hayes-arianne, baby-banks-john, banks-mia-leanne

Addition of AllergyIntolerance resources to:
- add refuted
- additional instances of none known and some nkda or nkfa
- additional some typical inactive instances (e.g. pet dander that was a childhood allergy)
- ensure there are biological, medication, and environment allergies added to the set
- aim to not include coding.display in the test data 
- otherwise introduce some variety across the test data resources

**Comment by heathfrankel** [comment]
15 new AllergyIntolerance instances uploaded to HL7 AU FHIR Server aucore instance
