### ISSUE TITLE
Assess and align changes from au core 0.3.0-ballot

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-test-data#9]
AU Core 0.3.0-ballot amended some Patient, Practitioner, PractitionerRole, Organization, Location resources instances for ballot purposes. Review of those changes in AU Core for any necessary alignment / improvement needs to be done. 

Noting they do not have to be exactly aligned.

**Comment by StephThaoOng** [comment]
Done. For personas retained that were not derived from Services Australia (SA) data, they either had demographics not present in the SA data or had to be retained at present due to the multiple codings issue on the FHIR server.
